-- MySQL Script generated by MySQL Workbench
-- Sat Nov 25 14:14:27 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema tasks
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tasks
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tasks` DEFAULT CHARACTER SET utf8 ;
USE `tasks` ;

-- -----------------------------------------------------
-- Table `tasks`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tasks`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `nome_usuario` VARCHAR(55) NOT NULL,
  `matricula_usuario` VARCHAR(75) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tasks`.`materia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tasks`.`materia` (
  `idmateria` INT NOT NULL AUTO_INCREMENT,
  `nome_materia` VARCHAR(75) NOT NULL,
  `data_criacao` DATETIME NOT NULL,
  `data_atualizacao` DATETIME NOT NULL,
  `usuario_idusuario` INT NOT NULL,
  PRIMARY KEY (`idmateria`),
  INDEX `fk_materia_usuario1_idx` (`usuario_idusuario` ASC),
  CONSTRAINT `fk_materia_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `tasks`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tasks`.`tarefa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tasks`.`tarefa` (
  `idtarefa` INT NOT NULL AUTO_INCREMENT,
  `nome_tarefa` VARCHAR(75) NOT NULL,
  `descricao_tarefa` TEXT NULL,
  `tempo_lembrete` DATETIME NULL,
  `data_criacao` DATETIME NOT NULL,
  `data_atualizacao` DATETIME NOT NULL,
  `materia_idmateria` INT NOT NULL,
  PRIMARY KEY (`idtarefa`),
  INDEX `fk_atividade_materia1_idx` (`materia_idmateria` ASC),
  CONSTRAINT `fk_atividade_materia1`
    FOREIGN KEY (`materia_idmateria`)
    REFERENCES `tasks`.`materia` (`idmateria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
