-- MySQL Script generated by MySQL Workbench
-- Mon Nov 20 14:06:38 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema tasks
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tasks
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tasks` DEFAULT CHARACTER SET utf8 ;
USE `tasks` ;

-- -----------------------------------------------------
-- Table `tasks`.`atividade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tasks`.`atividade` (
  `idatividade` INT NOT NULL AUTO_INCREMENT,
  `nome_tarefa` VARCHAR(75) NOT NULL,
  `descricao_tarefa` TEXT NULL,
  `tempo_lembrete` DATETIME NULL,
  `atividadecol` VARCHAR(45) NULL,
  PRIMARY KEY (`idatividade`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tasks`.`materia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tasks`.`materia` (
  `idmateria` INT NOT NULL AUTO_INCREMENT,
  `nome_materia` VARCHAR(75) NOT NULL,
  `idatividade` INT NOT NULL,
  PRIMARY KEY (`idmateria`),
  INDEX `fk_materia_atividade_idx` (`idatividade` ASC),
  CONSTRAINT `fk_materia_atividade`
    FOREIGN KEY (`idatividade`)
    REFERENCES `tasks`.`atividade` (`idatividade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tasks`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tasks`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `nome_usuario` VARCHAR(55) NOT NULL,
  `matricula_usuario` VARCHAR(75) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `idmateria` INT NOT NULL,
  PRIMARY KEY (`idusuario`),
  INDEX `fk_usuario_materia1_idx` (`idmateria` ASC),
  CONSTRAINT `fk_usuario_materia1`
    FOREIGN KEY (`idmateria`)
    REFERENCES `tasks`.`materia` (`idmateria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
